ナビバーの実装
yanbaru-expert/team_project_47 pull request #35
Opened 2021-04-04 12:57 UTC by ryu8825

## issue 番号

close #11 

## 実装内容

- Bootstrapを使い，逆転教材のナビバーに近いものを作成。
  - 部分テンプレート app/views/layouts/_header.html.erb を作成。
  - 「タスク6」で作成された「新規登録・ログアウトなどのリンク」は削除。
  - ナビバーのリンクは，「新規登録」「ログイン」「ログアウト」と，「テキスト教材」ページのみ有効にし，他は href 属性を # にしておくこと
  - ナビバーは fixed-top クラスを利用して上に固定。
  - ナビバーに隠れないようなスタイルの調整も行うこと。
## 参考資料（必要があれば）
-  [【公式】Bootstrap（Navbar）](https://getbootstrap.jp/docs/4.5/components/navbar/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-04 13:01 UTC, ryu8825 reviewed
確認しました

2021-04-04 13:14 UTC, T-Tsujii requested changes

2021-04-04 13:14 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +  padding-top: 60px;
デベロッパーツールで高さを調べて決めた方がよいですね。フラッシュがナビバーの下に来るので，だいたいではよろしくないですね。

![スクリーンショット 2021-04-04 22 11 39](https://user-images.githubusercontent.com/52148373/113509877-d5395400-9592-11eb-8c63-44782a02fb3d.png)

2021-04-04 13:14 UTC, T-Tsujii commented on app/views/layouts/_header.html.erb
> +          <%= link_to "ログアウト", destroy_user_session_path, class: "nav-item nav-link active", method: :delete, data: { confirm: "Are you sure?" } %>
確認の文章は日本語で書いておいた方がよいですね。

2021-04-05 03:12 UTC, ryu8825 reviewed
以下2点のご確認よろしくお願いいたします。
- bodyのpaddig修正
- 確認文を日本語に修正

2021-04-05 03:12 UTC, ryu8825 commented on app/assets/stylesheets/application.scss
> +  padding-top: 56px;
- 60px から　56pxに変更いたしました。

2021-04-05 03:12 UTC, ryu8825 commented on app/views/layouts/_header.html.erb
> +          <%= link_to "ログアウト", destroy_user_session_path, class: "nav-item nav-link active", method: :delete, data: { confirm: "本当によろしいですか" } %>
- 日本語に変更いたしました。

2021-04-05 10:33 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-05 12:37 UTC, merged