動画教材のCSVインポート機能を実装 #10
yanbaru-expert/team_project_47 pull request #40
Opened 2021-04-07 23:37 UTC by KENTA-MITANI

## issue 番号

close #10

## 実装内容

- `bundle update`を実行
- `movie_data.csv`を修正
  - csvデータの各行末尾の `,,` を削除 
  - `高卒・アラサー 〜` にカラムtalk追記
- `db/seeds.rb`に `ImportCsv.movie_data` を追記
- `lib/import_csv.rb`にmovie_dataメソッド実装

## 参考資料（必要があれば）

- [やんばるエキスパート教材（CSVインポート）](https://www.yanbaru-code.com/texts/217)

## チェックリスト

- [x] GitHub で Files changed を確認
- [x] 影響し得る範囲のローカル環境での動作確認

2021-04-08 03:07 UTC, T-Tsujii requested changes

2021-04-08 03:07 UTC, T-Tsujii commented on lib/import_csv.rb
> +    puts "インポート完了!!"
テキスト教材もそうですが，「何」のインポート処理か分かるようにした方がよいですね。

2021-04-09 14:19 UTC, KENTA-MITANI commented on lib/import_csv.rb
> +    puts "インポート完了!!"
rails db:seed実行時の画面出力について
何のインポート処理かわかるように修正しました。
ご確認願います。

2021-04-09 14:23 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-10 13:22 UTC, merged