Feature/activeadmin
yanbaru-expert/team_project_47 pull request #47
Opened 2021-04-14 05:24 UTC by KENTA-MITANI

## issue 番号

close #14

## 実装内容

- gemファイルactiveadminとdeviseをインストール
- devie & activeadminのファイル をインストール
- adminリソース実装
- `db/seeds.rb`に管理者データ作成を実装
- 管理画面の日本語修化

## 参考文献

- [【公式】Active Admin](https://github.com/activeadmin/activeadmin)
- [やんばるエキスパート教材 管理者画面](https://www.yanbaru-code.com/texts/220)

## チェックリスト

- [x] GitHub で Files changed を確認
- [x] 影響し得る範囲のローカル環境での動作確認

2021-04-14 06:53 UTC, T-Tsujii requested changes

2021-04-14 06:53 UTC, T-Tsujii commented on Gemfile
> +gem 'devise'
すでに入っていますよ。
```suggestion
```

2021-04-14 06:53 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc)
なぜこの差分が入っているのでしょうか。
`develop` からブランチを切っていないのではありませんか。

以下を実行してdevelopからブランチを切ったことにしてもらえますか。

```
git fetch --prune
git rebase origin/develop
git push -f origin HEAD
```

ただ，コンフリクトした場合は`git rebase --abort` で取り消してそのままでもよいです。

2021-04-14 06:53 UTC, T-Tsujii commented on app/admin/users.rb
> +  permit_params :email, :encrypted_password
デフォルトのままですとユーザーを追加・編集ができません。
`app/admin/admin_users.rb` を参考にしてみましょう。

2021-04-15 08:21 UTC, KENTA-MITANI commented on Gemfile
> +gem 'devise'
gem 'devise'を削除いたしました。

2021-04-15 08:22 UTC, KENTA-MITANI commented on app/admin/users.rb
> +  permit_params :email, :encrypted_password
教えて頂いた参考元を見て、アカウントタブからユーザの追加・編集を行えるように修正致しました。

2021-04-15 08:23 UTC, KENTA-MITANI commented on app/controllers/movies_controller.rb
> +    @movies = Movie.where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc)
すみません。
最初developからブランチを切り忘れて作業していたかもしれません。
記載して頂いたgitコードを実行致しました。

2021-04-15 08:52 UTC, T-Tsujii requested changes

2021-04-15 08:52 UTC, T-Tsujii commented on app/admin/users.rb
> +    column :sign_in_count
この2つは users テーブルに存在しないので削っておきましょう。

2021-04-15 22:52 UTC, KENTA-MITANI commented on app/admin/users.rb
> +    column :sign_in_count
お世話になっております。
修正致しました。

2021-04-16 02:00 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-16 03:27 UTC, merged