Ruby/Rails動画教材ページにページネーションを追加
yanbaru-expert/team_project_47 pull request #48
Opened 2021-04-16 07:05 UTC by Ikue9510

## issue 番号
close #44 

## 実装内容
- Ruby/rails動画教材ページにページネーションを追加  

## 参考資料
- [kaminari徹底入門](https://qiita.com/nysalor/items/77b9d6bc5baa41ea01f3)
- [【Rails】kaminariでページネーションを実装](https://qiita.com/d0ne1s/items/58c3d0e08ce7ede94384)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## [スクリーンショット]
![E05E179E-D977-4B4B-A2F5-EEA501B19A2D_1_105_c](https://user-images.githubusercontent.com/77062221/114983766-f6bc0900-9ecb-11eb-9c7f-b11f94f6af51.jpeg)
![C5D0CCFB-A797-4815-8F7D-FE05908AD3FD_1_105_c](https://user-images.githubusercontent.com/77062221/114983802-00de0780-9ecc-11eb-8b0c-2a4502492fbf.jpeg)

## 備考
- ページネーションと動画カードのレイアウトが整っていません（ページネーション・動画の間に隙間がない）が、今週のMTGでご指摘いただいた箇所と合わせて別のissueを作成し、整える予定です。
- 上記スクリーンショットの通り、2ページ目のレベル番号も1ページ目からの続きとなるよう設定しました。

2021-04-16 07:10 UTC, T-Tsujii requested changes

2021-04-16 07:10 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +    @movies = Movie.page(params[:page]).per(18)
この書き方ですと，3行目が反映されませんよ。（絞り込みと並び替えが反映されない）

2021-04-16 07:53 UTC, Ikue9510 commented on app/controllers/movies_controller.rb
> +    @movies = Movie.page(params[:page]).per(18)
絞り込みと並び替えが反映されるよう修正いたしました。
また絞り込み後の動画が16本だったので、1ページあたりの表示動画数を18→9に減らし、ページネーションが機能するよう変更もしております。

2021-04-16 07:58 UTC, Ikue9510 commented on app/controllers/movies_controller.rb
> +    @movies = Movie.page(params[:page]).per(18)
念の為スクリーンショットも添付しております。
## [スクリーンショット]
<img width="1294" alt="スクリーンショット 2021-04-16 16 56 04" src="https://user-images.githubusercontent.com/77062221/114991733-e3616b80-9ed4-11eb-8c3b-9883fc9686e7.png">
<img width="1289" alt="スクリーンショット 2021-04-16 16 56 24" src="https://user-images.githubusercontent.com/77062221/114991740-e52b2f00-9ed4-11eb-9bc3-e963f8621111.png">

2021-04-16 08:40 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-19 10:48 UTC, T-Tsujii requested changes

2021-04-19 10:48 UTC, T-Tsujii commented on app/views/movies/index.html.erb
> +  <%= paginate @movies %>
divの閉じタグの位置がずれていませんか？

2021-04-27 03:57 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-27 03:59 UTC, merged