Railsテキスト教材一覧ページの実装　
yanbaru-expert/team_project_47 pull request #49
Opened 2021-04-18 06:51 UTC by ryu8825

## issue番号 

close #15 

## 実装内容
- Railsテキスト教材の一覧ページを作成
 
- ナビバーのテキスト教材ページへのリンクが機能するようにする

## 参考資料（必要があれば）

-  [【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
-   [【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-18 06:51 UTC, ryu8825 reviewed
確認しました

2021-04-19 01:18 UTC, T-Tsujii requested changes

2021-04-19 01:18 UTC, T-Tsujii commented on app/views/devise/shared/_error_messages.html 2.erb
> +<% if resource.errors.any? %>
` 2.erb` で終わるファイルが複数存在しています。削除しておいて下さい。

2021-04-19 01:18 UTC, T-Tsujii commented on config/routes.rb
>    resources :movies
ルーティングは必要なものだけとしましょう。動画の方もついでに絞っていただけますか。

```suggestion
  resources :texts, only: [:index, :show]
  resources :movies, only: [:index]
```

2021-04-19 01:18 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +<div class= "container-fluid" >
`container` クラスはapplication.html.erbに入っているので不要です。

2021-04-19 01:18 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +      <div class= "col-12 col-md-6 col-lg-4 text-card">
カードが詳細ページへのリンクとなるようにして下さい。

2021-04-19 22:56 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-19 23:02 UTC, merged