フッターの実装
yanbaru-expert/team_project_47 pull request #52
Opened 2021-04-24 07:09 UTC by ryu8825

## issue 番号

close #51 

## 実装内容

- フッターの実装
  - footerファイルの作成
  - 各種SNSへのリンク追加（リンクは＃）
  - scssファイルの修正

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-24 07:11 UTC, ryu8825 reviewed
- footerファイル作成。
- リンクを追加
- スタイル適用

2021-04-24 07:11 UTC, ryu8825 commented on app/assets/stylesheets/application.scss
> +// footer
footerについてのスタイル

2021-04-24 07:20 UTC, T-Tsujii requested changes

2021-04-24 07:20 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +  bottom: 0;
一番下ではありませんが，これでよいのでしょうか？

![スクリーンショット 2021-04-24 16 19 55](https://user-images.githubusercontent.com/52148373/115950903-eeda1580-a518-11eb-8249-642e4a560cf0.png)

2021-04-25 07:59 UTC, ryu8825 commented on app/views/layouts/_footer.html.erb
> +<footer class = "bg-primary">
- フッターの各リンク

2021-04-25 07:59 UTC, ryu8825 commented on app/assets/stylesheets/application.scss
> +}
- flexboxを活用

2021-04-25 08:48 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-25 11:34 UTC, merged