navbarの修正（元のアプリに近づけたものに戻す）
yanbaru-expert/team_project_47 pull request #58
Opened 2021-05-05 09:56 UTC by ryu8825

## issue 番号

close #57  

## 実装内容
- 「やんばるエキスパート」のロゴ、フォント変更
- ナビバーを全体的にやや右揃えとする
- マイページのタブボタン設定

## 参考資料
- #37 ナビバーの修正

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-05-05 09:57 UTC, ryu8825 reviewed
確認

2021-05-10 04:29 UTC, T-Tsujii requested changes
ハンバーガーメニューが動作していません。

```
yarn add bootstrap@~4.5.1
```

を実行してBootstrapのバージョンを下げて下さい。

2021-05-11 13:41 UTC, omoto-ryuya commented on app/views/layouts/_header.html.erb
> +    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
6行目のdata-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
と
9行目のid="navbarSupportedContent"　が一致していませんでした。

2021-05-11 22:39 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-12 00:05 UTC, merged