動画&テキスト教材に検索機能実装
yanbaru-expert/team_project_47 pull request #63
Opened 2021-05-11 09:11 UTC by KENTA-MITANI

## 実装内容

- テキスト教材ページに検索機能実装
- 動画教材ページに検索機能実装

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [x] GitHub で Files changed を確認
- [x] 影響し得る範囲のローカル環境での動作確認

## 備考

検索機能は、ransackを使って実装しました。

2021-05-11 09:47 UTC, T-Tsujii requested changes

2021-05-11 09:47 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +}
`.container` は Bootstrap が使用しているクラスですので，他のクラス名にしましょう。

2021-05-11 09:47 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +    @movies = @q.result.page(params[:page]).per(9)
この書き方では3行目が無視されるので，PHPの動画が含まれてしまいます。

2021-05-12 04:16 UTC, KENTA-MITANI commented on app/assets/stylesheets/application.scss
> +}
クラス名をsearchに変更致しました。

2021-05-12 04:16 UTC, KENTA-MITANI commented on app/controllers/movies_controller.rb
> +    @movies = @q.result.page(params[:page]).per(9)
修正いたしましたので確認願います。

2021-05-12 07:48 UTC, T-Tsujii requested changes

2021-05-12 07:48 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +    @movies = @q.result.page(params[:page]).per(9)
ページネーションは最後に反映しなければなりません。この形式ではありませんか。

```suggestion
    @q = Movie.where(genre: ["basic", "git", "ruby", "rails"]).ransack(params[:q])
    @movies = @q.result.order(id: :asc).page(params[:page]).per(9)
```

テキスト教材も同様に修正しましょう。

2021-05-12 08:53 UTC, KENTA-MITANI commented on app/controllers/movies_controller.rb
> +    @movies = @q.result.page(params[:page]).per(9)
指摘頂いた通りページネーションを最後にするように変更致しました。

2021-05-12 09:04 UTC, KENTA-MITANI commented on app/controllers/movies_controller.rb
> +    @movies = @q.result.page(params[:page]).per(9)
テキスト教材もページネーションを修正致しました。

2021-05-12 11:12 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-12 11:12 UTC, merged