よくある質問集ページの追加
yanbaru-expert/team_project_47 pull request #64
Opened 2021-05-21 16:00 UTC by Ikue9510

close #53 

## 実装内容
- 管理画面から質問と回答を投稿できるような機能の追加。
  - 質問のCSVデータのインポート
  - 質問集ページに検索機能実装
  - 管理者画面への追加と日本語化

## 参考資料
- 検索機能
  - [やんばるエキスパートアプリ](https://www.yanbaru-code.com/texts/221)
- 管理者画面
  - [やんばるエキスパートアプリ](https://www.yanbaru-code.com/texts/220)
- [【公式】Bootstrap forms](https://getbootstrap.jp/docs/4.4/components/forms/)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-05-21 23:45 UTC, T-Tsujii requested changes

2021-05-21 23:45 UTC, T-Tsujii commented on db/seeds.rb
>  user1 = User.create!(email: "satou@example.com", password: "password")
`rails db:seed` 実行時にエラーがでますので，ファイル全体をこんな感じで書き換えて下さい。

```rb
require "import_csv"

# テストユーザー情報
EMAIL = "test@example.com"
PASSWORD = "password"
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "password"

# テストユーザーが存在しないときだけ作成
User.find_or_create_by!(email: EMAIL) do |user|
  user.password = PASSWORD
  puts "ユーザーアカウントの作成に成功しました。"
end

AdminUser.find_or_create_by!(email: ADMIN_EMAIL) do |admin_user|
  admin_user.password = ADMIN_PASSWORD
  puts "管理者ユーザーアカウントの作成に成功しました。"
end

ImportCsv.text_data
ImportCsv.movie_data
ImportCsv.question_data
```

2021-05-21 23:45 UTC, T-Tsujii commented on app/views/questions/index.html.erb
> +
こちら機能していないようです。実装方法も少々ややこしいので，削除してしまってもよいと思います。
表示するならば，JavaScriptではなくRansackを使用する前提でよいですので，機能するようにした方がよいでしょう。

2021-05-21 23:45 UTC, T-Tsujii commented on app/views/questions/index.html.erb
> +      <input type="search" class="form-control" id="q_title_cont" name="q[title_cont]">
できれば検索ボタンクリック後に入力内容が保持されるようにした方がよいですね。

https://www.yanbaru-code.com/texts/221
にあるような `f.search_field` を使用するとよいでしょう。

2021-05-24 06:55 UTC, Ikue9510 commented
コメントありがとうございます。
ご指摘いただいた箇所の修正を行いましたのでお手数ですが、再度の確認お願いします。

2021-05-24 11:11 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-24 12:02 UTC, merged